version: '3'
services:
  accounts:
    build:
      context: ./account
    ports:
      - "8000:80"
    container_name: account
  shop:
    build:
      context: ./shop
    ports:
      - "8001:80"
    container_name: shop
  order:
    build:
      context: ./order
    ports:
      - "8002:80"
    container_name: order
  nginx:
    build:
      context: ./nginx
    ports:
      - "7777:7777"
