version: '3'
services:
  accounts:
    build: ./accounts
    ports:
      - "8001:8001"
    depends_on:
      - postgres
  shop:
    build: ./shop
    ports:
      - "8002:8002"
    depends_on:
      - postgres
  order:
    build: ./order
    ports:
      - "8003:8003"
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accounts
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./db/accounts.sql:/docker-entrypoint-initdb.d/accounts.sql
      - ./db/shop.sql:/docker-entrypoint-initdb.d/shop.sql
      - ./db/order.sql:/docker-entrypoint-initdb.d/order.sql
